### ISSUE TITLE
CAN THIS WORK ON THE BROWSER ENVIRONMENT

### ISSUE THREAD

**Issue by AlijiEmmanuel-dev** [cwysong85/sipjs-udp#18]
Can this Sip UDP connection work on the browser environment? If so, how does one go about implementation, curreently there is no documentation available.

**Comment by cwysong85** [comment]
This is specifically for NodeJS server environment. I would recommend using SIP.js official library here: https://github.com/onsip/sip.js/ - They support web browsers.
