### ISSUE TITLE
Always reply busy on new call invite

### ISSUE THREAD

**Issue by abelmferreira** [cwysong85/sipjs-udp#8]
I'm successfully registering with you codes on a sip server.
For developer purpose, how can i always reply on busy on any new call invite?
Im trying a lot but without success... can you give me some orientations?

**Comment by cwysong85** [comment]
You should be able to use the `terminate()` function that's available in the session. Below is an example of how to do this.

```
// on invite event
server.on('invite', (session) => {
    session.terminate({
        statusCode: '486',
        reasonPhrase: 'Busy Here'
    })
})
```

Let me know if this works for you!

**Comment by abelmferreira** [comment]
Thanks!!!
Im using your example b2bua.js adding only the confs necessary to register.
Im seeing tha the response was sended and the logs show closing Invite, but other sip client that makes that makes the call dont understand the response, it still keep in dialing state.


Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.sipmessage | header "Content-Disposition" not present

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.dialog | new UAS dialog created with status EARLY

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | b2bua.mediaHandler | ---> First Step :: new inbound call

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | b2bua.mediaHandler | ---> Second Step :: send the original ingress caller description

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.transaction.ict | Timer D expired for INVITE client transaction z9hG4bK2257776

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.sipmessage | header "Content-Disposition" not present

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.dialog | new UAS dialog created with status EARLY

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | b2bua.mediaHandler | ---> Third Step :: Invite was answered, set egress description and call ingress success method to move forward

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | b2bua.server | ---> Fourth Step :: receive invite event from stack and accept the call

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.inviteservercontext | rejecting RTCSession

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.inviteservercontext | closing INVITE session kGrrmwoVsCx0G8NyxVlrdw..46f07365

Fri Apr 10 2020 20:09:52 GMT-0300 (GMT-03:00) | sip.dialog | dialog kGrrmwoVsCx0G8NyxVlrdw..lsmvv9r5dc46f07365 deleted

Fri Apr 10 2020 20:09:54 GMT-0300 (GMT-03:00) | sip.transaction.nist | Timer J expired for non-INVITE server transaction z9hG4bK-524287-1---ec20082f9fa9ac7c

**Comment by abelmferreira** [comment]
Im doing more tests and sniffer the communication between this node app and the real sip server, I see that the reply was never send back to the server again.
Im trying understand were i can fix this.


The register was success... but the others reply or informations.

```javascript
class MediaHandler {
  constructor(session) {
    console.log('--------> constructor')
    this.session = session
    this.ua = session.ua
    this.logger = session.ua.getLogger('b2bua.mediaHandler')
    session.on('invite', (session) => console.log('--------> session invite context--->') )
  }
  close() {}
  render() {}
  mute() {}
  unmute() {}
  getDescription(onSuccess, onFailure, mediaHint) {
    console.log('--------> getDescription')
    onSuccess()
  }
  setDescription(description, onSuccess, onFailure) {
    console.log('--------> setDescription')
    onSuccess()
  }
}

const server = new SIPUDP.UA({
  uri: `sip:${exten}@${host}:${port}`,
  bind: process.env.BIND || '0.0.0.0',
  autostart: true,
  register: true,
  traceSip: false,
  doUAS: false,
  authorizationUser: authid,
  password: password,
  bindport: (Math.floor(Math.random() * (Math.floor(30000) - Math.ceil(10000))) + 10000).toString(), //dyn local bind port
  registerExpires: process.env.EXPIRES || 90,
  noAnswerTimeout: 15,
  displayName: 'Dummy Client',
  user_agent: 'Node JsSIP',
  mediaHandlerFactory: (session) => {
    return new MediaHandler(session)
  }
})

server.on('connected', (t) => console.log('--------> server connected') )

// on invite event
server.on('invite', (session) => {
  console.log('--------> server invite context')
  session.terminate({
    status_code: '486',
    reason_phrase: 'Busy Here'
  })
})

server.on('registered', e => console.log(`SIP registered to ${e.via.host} on ${e.headers['User-Agent'][0].raw} with ${e.headers.Contact[0].raw}`))
server.on('registrationFailed', (response, cause) => console.log(`SIP registrationFailed ${response} ${cause}`))
server.on('unregistered', (response, cause) => console.log(`SIP unregistered ${response} ${cause}`))
server.on('message', msg => console.log('SIP message', msg, body))
server.on('disconnected', e => console.log('Disconnected', e))
```

The log output was

```
Sat Apr 11 2020 09:47:27 GMT-0300 (GMT-03:00) | sip.ua | connection state set to 0
--------> server connected
SIP registered to xxx on SIPPhoneSystem (504) with <sip:1803@xxx:5060;transport=udp>;reg-id=1;+sip.instance="<urn:uuid:0da7f6b1-598e-416f-b0f4-eb336d20edb9>";expires=90
Sat Apr 11 2020 09:47:35 GMT-0300 (GMT-03:00) | sip.sipmessage | header "Content-Disposition" not present
Sat Apr 11 2020 09:47:35 GMT-0300 (GMT-03:00) | sip.dialog | new UAS dialog created with status EARLY
--------> constructor
--------> setDescription
--------> session invite context--->
--------> server invite context
Sat Apr 11 2020 09:47:35 GMT-0300 (GMT-03:00) | sip.inviteservercontext | rejecting RTCSession
Sat Apr 11 2020 09:47:35 GMT-0300 (GMT-03:00) | sip.inviteservercontext | closing INVITE session wQbPaRmjeoGmZlr9miD5rA..26918a4e
Sat Apr 11 2020 09:47:35 GMT-0300 (GMT-03:00) | sip.dialog | dialog wQbPaRmjeoGmZlr9miD5rA..26j37t9v2326918a4e deleted
```

Looking at wireshark, only REGISTER was sended to server

![image](https://user-images.githubusercontent.com/2151109/79044208-548f8400-7bda-11ea-9d3e-c02f6d0cbd4f.png)

And enabling traceSIP i can see that the messages blocks send to remote party, the TRYING for example, is sending to local party, not to remote party

```
Sat Apr 11 2020 09:58:09 GMT-0300 (GMT-03:00) | sip.transport | sending UDP message:

SIP/2.0 100 Trying
Via: SIP/2.0/UDP 172.20.10.11:5060;branch=z9hG4bK-524287-1---72c0612ed4e6500e;rport
To: <sip:1803@xxx>
From: "Teste User Remote"<sip:1005@xxx:5060>;tag=7337436a
Call-ID: DvNsysT4hy8QSAr9AfPFRw..
CSeq: 1 INVITE
Supported: outbound
User-Agent: sipjs-udp/0.0.14
Content-Length: 0
```

**Comment by cwysong85** [comment]
How are you running your application? Is this in a container or is this
local on your computer?

**Comment by abelmferreira** [comment]
A extra information is that i change the source to allow diferente local bind port  from the server uri port, because in production i will need run this app on same sip server.

A real sip server (like asterisk) and this node app code on same server.

Changes in this [commit](https://github.com/abelmferreira/sipjs-udp/commit/5d59cbb1ed1ca6448b21f5082ab2ee892c49e128)

The tests im running on my local machine, withou docker, just running "node script.js" on console, registering on a real SIP server on internet.

**Comment by abelmferreira** [comment]
@cwysong85 sniffering more i see that all reply messages was sended to 172.20.10.11 because this ip was informed from server in Via parte of the header. This is the private local ip from the server.

Where can i change to modify this considering the ip sended on FROM header part?

Adding this peace of code on transport.js

```
            if (host === '172.20.10.11') {
                console.log('--------------- changin ip from 172 to 52')
                host = '52.67.169.186'
            }
```

transport.js, with the hack code to change destination address
```
    Transport.prototype = {
        /**
         * Send a message.
         * @param {SIP.OutgoingRequest|String} msg
         * @returns {Boolean}
         */
        send: function(host, port, msg) {
            var message = msg.toString();

            if (host === '172.20.10.11') {
                console.log('--------------- changin ip from 172 to 52')
                host = '52.67.169.186'
            }

            if (this.ua.configuration.traceSip === true) {
                this.logger.log('sending UDP message:\n\n' + message + '\n');
            }

            var msgToSend = new Buffer(message);

            this.server.send(msgToSend, 0, msgToSend.length, port, host, function(err) {
                if (err) {
                    console.log(err);
                    return false;
                }
            });
            return true;
        },
```

doing this the SIP server understand the trying message and start ring to the calling party.

But no message sip 486 busy was sended. :(

**Comment by abelmferreira** [comment]
About not replying Busy here was my mistake.
You writed statusCode and reasonPhrase as parameter and Camel Case style.
But at documentation of jssip.js was Snake Case and at one of the milions test i change this.
Changed back to Camel Case the message was correct sended.

![image](https://user-images.githubusercontent.com/2151109/79047399-ab9e5480-7bec-11ea-9aaa-e37415950a3e.png)
