### ISSUE TITLE
Can we use sipjs-udp in an Angular project?

### ISSUE THREAD

**Issue by NOualet** [cwysong85/sipjs-udp#9]
I'm looking for a sip library in udp for an angular project. I wanted to know if your library works well on Angular? This may sound like a silly question, but I'm not very familiar with angular, typescript and associated libraries yet.

**Comment by cwysong85** [comment]
This particular library is for NodeJS (think server side) and uses the UDP
transport which isn't available on a Web Browser. I would recommend using
this library: https://sipjs.com/

**Comment by NOualet** [comment]
I'm looking for a sip library using UDP. So your library is a match, right?

**Comment by NOualet** [comment]
So you're going to make a guide as on https://sipjs.com/?

**Comment by cwysong85** [comment]
I’m a bit confused. Angular is a front-end library and cannot consume this
library because the web browser doesn’t support UDP.

**Comment by NOualet** [comment]
So I can use your library with which framework?
